spring.application.name=letter-app

# Banco H2 em memória
spring.datasource.url=jdbc:h2:mem:letterdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Console H2 acessível em http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Habilita leitura de @ConfigurationProperties
spring.config.import=optional:
